version: '3.7'
services:
  ana-microservice-nodejs:
    build: ./docker/dev/clearlinux
    container_name: ana-microservice-nodejs
    ports:
      - 3000:3000
    depends_on:
      - ana-microservice-mysql
    volumes:
      - ./:/usr/src/

  ana-microservice-mysql:
    image: mysql:8.0.28
    container_name: ana-microservice-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=ana
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql-db:/docker-entrypoint-initdb.d
      - ./storage/.db:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
